remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 테마 설정
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 사이트 설정
title: "AD윤영스윗투웬티HD"
subtitle: "뇌정리노트"
name: "yunYoung e"
description: "2026년 목표: 개발로 월급받기<br>추가 정보 없음"
url: "https://yunrry.github.io"
repository: "yunrry/yunrry.github.io"

# 작성자 정보
author:
  name: "yunYoung e"
  avatar: "/assets/images/mandu.jpeg"
  bio: "2026년 목표: 개발로 월급받기<br>"
  location: "Seoul, Korea"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:yunryy329@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yunrry"
  github-contributions: true


# 기본 설정
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Front Matter 기본값
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      sidebar:
        nav: "categories"

    # 페이지 기본값
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      sidebar:
        nav: "categories"

  - scope:
      path: "contents"
    values:
      layout: null

include:
  - _pages
  - _algorithm
  - _cs
  - _dev
  - _language
  - _inclueds
  - assets/contents
  
# exclude:
#   - assets/contents/

head_scripts:
  - /assets/js/custom.js


markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Liquid 설정 - 중요!
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false