remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 테마 설정
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 사이트 설정
title: "내 블로그"
subtitle: "부제목"
name: "본인 이름"
description: "블로그 설명"
url: "https://yunrry.github.io"
repository: "yunrry/yunrry.github.io"

# 작성자 정보
author:
  name: "본인 이름"
  avatar: "/assets/images/mandu.jpeg"
  bio: "간단한 소개"
  location: "Seoul, Korea"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your-email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yunrry"

# 기본 설정
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Front Matter 기본값
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true